In [2]:
import torch

In [14]:
x = torch.arange(12) #行向量
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
x.shape     # 张量的形状

torch.Size([12])

In [8]:
x.numel()   # 张量元素个数

12

In [16]:
x.reshape(3, 4) # 改变张量形状

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
torch.zeros((2, 3, 4)) # 全零张量

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.randn(3 , 4) #标准高斯分布

tensor([[ 0.5311, -0.5710, -0.8862, -0.4112],
        [-0.8338,  0.4267, -0.5565, -0.6354],
        [ 0.6344, -1.3637,  1.0897,  0.3090]])

In [17]:
torch.tensor([[2, 1,4,3],[1,2,3,4],[4,3,2,1]]) # Python列表转张量

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 运算符

In [3]:
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # 按元素运算，即每个元素和对应元素做算数运算

(tensor([ 3,  4,  6, 10]),
 tensor([-1,  0,  2,  6]),
 tensor([ 2,  4,  8, 16]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1,  4, 16, 64]))

In [24]:
x = x.reshape(-1 ,2)
y = y.reshape(-1, 2)
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1) # 张量连接，支持按不同的轴合并

(tensor([[1, 2],
         [4, 8],
         [2, 2],
         [2, 2]]),
 tensor([[1, 2, 2, 2],
         [4, 8, 2, 2]]))

In [5]:
x.sum()  # 张量求和
x.mean(0, dtype=float) # 求平均值

tensor(3.7500, dtype=torch.float64)

In [8]:
x = torch.arange(3).reshape((3,1))
y = torch.arange(2).reshape((1, 2))
print(x),print(y)
x + y           # 形状不一样的张量相加，自动进行广播，复制缺少的行和列，自动对齐

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 索引和切片

In [3]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
x[-1], x[1:3]  # -1 取最后一行

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [6]:
x[1:2, :] = 12   # 指定索引赋值，：表示延轴1的所有元素
x

tensor([[ 0.,  1.,  2.,  3.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])