In [1]:
import torch

In [2]:
A = torch.arange(12, dtype=torch.float32).reshape(3,4)
B = A.clone()
A, A + B   # 按元素相加，不改变张量的形状

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.]]))

In [3]:
A * B   # 哈达玛积

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.]])

In [5]:
A, A.sum(),  A.sum(axis=0)  #求和，降维，按0轴求和

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor(66.),
 tensor([12., 15., 18., 21.]))

In [9]:
x = torch.arange(4, dtype = torch.float32)
y = x.clone()
x, y, torch.dot(x, y)  #向量点积等于向量相乘然后求和

(tensor([0., 1., 2., 3.]), tensor([0., 1., 2., 3.]), tensor(14.))

### 矩阵乘法

In [10]:
A = torch.arange(20, dtype = torch.float32).reshape(5, 4)
x = torch.arange(4, dtype = torch.float32)
A, x, torch.mv(A, x)   # 矩阵向量积， 矩阵行向量与向量x进行点积

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

In [11]:
B = torch.ones(4, 3)
A, B, torch.mm(A, B)  # 矩阵乘法，是A矩阵的行向量与B矩阵的列向量进行点积。

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

### 范数，向量大小

In [12]:
u = torch.tensor([3.0, -4.0])
torch.norm(u) # 对向量元素的平方和进行开方

tensor(5.)

In [14]:
A = torch.ones((4, 9))
A, torch.norm(A)  # 矩阵的范数是矩阵元素的平方和的平方根，也即每个元素平方相加然后开方

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 tensor(6.))